project:
  type: website
  output-dir: docs

website:
  title: "Bristol Active Matter Group"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "Reading"
        href: reading.qmd
      - text: "About"
        href: about.qmd
      - text: "Tutorial"
        href: hello.qmd

format:
  html:
    theme: flatly
    toc: true