project:
  type: website
  output-dir: docs

website:
  title: "Bristol Active Matter Group"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true